export const ConversationState = {
  LANGUAGE_SELECTION: 'LANGUAGE_SELECTION',
  PRIVACY_NOTICE: 'PRIVACY_NOTICE',
  MAIN_MENU: 'MAIN_MENU',
  PRIVACY_DETAILS: 'PRIVACY_DETAILS',
  HELP: 'HELP',
  SUBMISSION_INSTRUCTIONS: 'SUBMISSION_INSTRUCTIONS',
  WAITING_FOR_PRAYER: 'WAITING_FOR_PRAYER',
  REVIEWING_REQUEST: 'REVIEWING_REQUEST',
  SUBMISSION_PROCESSING: 'SUBMISSION_PROCESSING',
} as const;

export type ConversationStateType = (typeof ConversationState)[keyof typeof ConversationState];
