export const ErrorCode = {
  INVALID_INPUT: 'INVALID_INPUT',
  REQUEST_TOO_LONG: 'REQUEST_TOO_LONG',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  DISPATCH_ALREADY_RUNNING: 'DISPATCH_ALREADY_RUNNING',
  TELEGRAM_SEND_FAILED: 'TELEGRAM_SEND_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
