export const ErrorCode = {
  INVALID_INPUT: 'INVALID_INPUT',
  REQUEST_TOO_LONG: 'REQUEST_TOO_LONG',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  DISPATCH_ALREADY_RUNNING: 'DISPATCH_ALREADY_RUNNING',
  TELEGRAM_SEND_FAILED: 'TELEGRAM_SEND_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Phase 5 Additions
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_DRAFT: 'INVALID_DRAFT',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
